In [1]:
import pandas as pd

In [25]:
df=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\car_price_analysis\car_price_prediction_.csv")

In [85]:
df.head(10)

,car_id,brand,year,engine_size,fuel_type,transmission,total_km_travled,condition,price,model,price_category
0,1,Tesla,2016,2.3,Electric,Manual,114832,Like_New,26613.92,Model X,Affordable
1,2,BMW,2018,4.4,Electric,Manual,143190,Like_New,14679.61,5 Series,Affordable
2,3,Audi,2013,4.5,Electric,Manual,181601,Like_New,44402.61,A4,Mid-range
3,4,Tesla,2011,4.1,Electric,Automatic,68682,New,86374.33,Model Y,Luxury
4,5,Ford,2009,2.6,Diesel,Manual,223009,Used,73577.10,Mustang,Expensive
5,6,Audi,2019,2.4,Diesel,Automatic,246553,Used,88969.76,Q7,Luxury
6,7,Audi,2020,4.0,Electric,Automatic,135486,Like_New,63498.75,Q5,Expensive
7,8,Tesla,2017,5.3,Electric,Automatic,83030,New,17381.19,Model Y,Affordable
8,9,Honda,2023,5.7,Electric,Manual,120360,Like_New,15905.62,Civic,Affordable
9,10,Ford,2010,1.5,Electric,Automatic,135009,Like_New,9560.22,Explorer,Affordable

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB

In [28]:
df.describe()

           Car ID       Year  Engine Size        Mileage         Price
count  2500.00000  2500.0000  2500.000000    2500.000000   2500.000000
mean   1250.50000  2011.6268     3.465240  149749.844800  52638.022532
std     721.83216     6.9917     1.432053   87919.952034  27295.833455
min       1.00000  2000.0000     1.000000      15.000000   5011.270000
25%     625.75000  2005.0000     2.200000   71831.500000  28908.485000
50%    1250.50000  2012.0000     3.400000  149085.000000  53485.240000
75%    1875.25000  2018.0000     4.700000  225990.500000  75838.532500
max    2500.00000  2023.0000     6.000000  299967.000000  99982.590000

In [44]:
df.isnull().sum()

car_id          0
brand           0
year            0
engine_size     0
fuel_type       0
transmission    0
mileage         0
condition       0
price           0
model           0
dtype: int64

In [63]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df.rename(columns={"mileage":"total_km_travled"},inplace=True)

In [64]:
df.columns

Index(['car_id', 'brand', 'year', 'engine_size', 'fuel_type', 'transmission',
       'total_km_travled', 'condition', 'price', 'model'],
      dtype='object')

In [41]:
df.loc[df["brand"]=="Tesla","fuel_type"]="Electric"

In [56]:
df.groupby(["brand","fuel_type"]).size().reset_index(name="count")

       brand fuel_type  count
0       Audi    Diesel     97
1       Audi  Electric     94
2       Audi    Hybrid     81
3       Audi    Petrol     96
4        BMW    Diesel     92
5        BMW  Electric     91
6        BMW    Hybrid     86
7        BMW    Petrol     89
8       Ford    Diesel     85
9       Ford  Electric     85
10      Ford    Hybrid     86
11      Ford    Petrol     91
12     Honda    Diesel    103
13     Honda  Electric     75
14     Honda    Hybrid     87
15     Honda    Petrol     87
16  Mercedes    Diesel     83
17  Mercedes  Electric     82
18  Mercedes    Hybrid     80
19  Mercedes    Petrol    108
20     Tesla  Electric    348
21    Toyota    Diesel    107
22    Toyota  Electric     87
23    Toyota    Hybrid     96
24    Toyota    Petrol     84

In [66]:
df.groupby("fuel_type")["total_km_travled"].mean().reset_index(name="mileage")

  fuel_type        mileage
0    Diesel  150980.511464
1  Electric  145929.686775
2    Hybrid  153059.600775
3    Petrol  151348.681081

In [58]:
df.duplicated().sum()

np.int64(0)

In [73]:
labels = ["Affordable", "Mid-range", "Expensive", "Luxury"]
df["price_category"]=pd.qcut(df["price"],4,labels=labels)

In [74]:
df[["price_category","brand"]].head(10)

  price_category  brand
0     Affordable  Tesla
1     Affordable    BMW
2      Mid-range   Audi
3         Luxury  Tesla
4      Expensive   Ford
5         Luxury   Audi
6      Expensive   Audi
7     Affordable  Tesla
8     Affordable  Honda
9     Affordable   Ford

In [78]:
labels=["New","Like_New","Used"]
df["condition"]=pd.qcut(df["total_km_travled"],3,labels=labels)

In [87]:
from sqlalchemy import create_engine
import pandas as pd
engine=create_engine("mysql+pymysql://root:prince@localhost/car_price_analysis")
df.to_sql("car", engine, index=False, if_exists="replace")

2500

In [88]:
df.to_sql("car", engine, index=False, if_exists="replace")

2500

In [93]:
df.to_csv("car_details_analysis.csv", index=False)